Updated the git action yaml file

diff --git a/.github/workflows/cypress-aws-ci.yml b/.github/workflows/cypress-aws-ci.yml
--- a/.github/workflows/cypress-aws-ci.yml
+++ b/.github/workflows/cypress-aws-ci.yml
@@ -38,6 +38,12 @@ jobs:
       - name: Clean previous Cypress reports
         run: rm -rf cypress/reports
 
+      - name: Prepare report directory
+        run: |
+            rm -rf $REPORT_DIR
+            mkdir -p $REPORT_DIR
+
+
 
   # -------------------------------------------------
   # 2. Run Cypress Tests
@@ -50,6 +56,8 @@ jobs:
     env:
       NODE_TLS_REJECT_UNAUTHORIZED: "0"
       BASE_URL: ${{ secrets.BASE_URL }}
+      RUN_ID: run-${{ github.run_number }}
+      REPORT_DIR: cypress/reports/run-${{ github.run_number }}
 
     steps:
       - name: Capture Start Time
@@ -78,42 +86,35 @@ jobs:
         run: |
           npx cypress run \
             --reporter mochawesome \
-            --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true || true
+            --reporter-options reportDir=$REPORT_DIR,overwrite=false,html=false,json=true || true
 
       - name: Merge mochawesome reports
         run: |
-          rm -f cypress/reports/output.json
-          rm -rf cypress/reports/html
-          mkdir -p cypress/reports
+         JSON_FILES=$(ls $REPORT_DIR/mochawesome*.json 2>/dev/null || true)
 
-          JSON_FILES=$(ls cypress/reports/mochawesome*.json 2>/dev/null || true)
+         if [ -z "$JSON_FILES" ]; then
+         echo "⚠️ No mochawesome JSON files found. Skipping merge."
+         exit 0
+         fi
 
-          if [ -z "$JSON_FILES" ]; then
-          echo "⚠️ No mochawesome JSON files found. Skipping merge."
-          exit 0
-          fi
+         npx mochawesome-merge $JSON_FILES > $REPORT_DIR/output.json
 
-          echo "🟢 Merging mochawesome JSON files:"
-          echo "$JSON_FILES"
+         node -e "JSON.parse(require('fs').readFileSync('$REPORT_DIR/output.json','utf8'))"
 
-          npx mochawesome-merge $JSON_FILES > cypress/reports/output.json
+         npx mochawesome-report-generator \
+         $REPORT_DIR/output.json \
+         --reportDir $REPORT_DIR \
+         --reportFilename index \
+         --charts true
 
-    
-          node -e "JSON.parse(require('fs').readFileSync('cypress/reports/output.json','utf8'))"
+         echo "✅ Mochawesome report generated at $REPORT_DIR"
 
-          npx mochawesome-report-generator \
-          cypress/reports/output.json \
-          --reportDir cypress/reports/html \
-          --reportFilename index \
-          --charts true
-
-          echo "✅ Mochawesome HTML report generated"
 
       - name: Upload Cypress Reports (Artifact)
         uses: actions/upload-artifact@v4
         with:
-          name: cypress-reports
-          path: cypress/reports
+          name: cypress-reports-${{ github.run_number }}
+          path: ${{ env.REPORT_DIR }}
 
   # -------------------------------------------------
   # 3. Upload to S3
@@ -127,8 +128,8 @@ jobs:
       - name: Download Test Artifact
         uses: actions/download-artifact@v4
         with:
-          name: cypress-reports
-          path: cypress/reports
+          name: cypress-reports-${{ github.run_number }}
+          path: cypress/reports/run-${{ github.run_number }}
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
@@ -139,11 +140,17 @@ jobs:
 
       - name: Upload Reports to S3 (Public Folder)
         run: |
-          if [ -d "cypress/reports" ]; then
-            aws s3 cp cypress/reports s3://abhinandan-cypress-results/reports/ --recursive
-          else
-            echo "❌ reports folder missing"
-          fi
+         RUN_DIR="run-${{ github.run_number }}"
+         LOCAL_PATH="cypress/reports/$RUN_DIR"
+         S3_PATH="s3://abhinandan-cypress-results/reports/$RUN_DIR/"
+
+         if [ -d "$LOCAL_PATH" ]; then
+         echo "⬆ Uploading reports from $LOCAL_PATH to $S3_PATH"
+         aws s3 cp "$LOCAL_PATH" "$S3_PATH" --recursive
+         else
+         echo "❌ Report folder missing: $LOCAL_PATH"
+         exit 1
+         fi
 
       - name: Build Screenshot Links
         run: |
@@ -209,7 +216,7 @@ jobs:
 
       - name: Send SNS notification
         run: |
-          PUBLIC_URL="https://abhinandan-cypress-results.s3.ap-south-2.amazonaws.com/reports/index.html"
+          PUBLIC_URL="https://abhinandan-cypress-results.s3.ap-south-2.amazonaws.com/reports/run-${{ github.run_number }}/index.html"
 
           MSG="Cypress CI/CD Pipeline Completed!
 
